apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: demo
        resources:
          limits:
            cpu: 1500m
            memory: 12000Mi
          requests:
            cpu: 100m
            memory: 1000Mi

