apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: adikarthik/demo
        name: demo
        ports:
        - containerPort: 9090
        resources: {}
      - image: adikarthik/rest
        name: rest 
        ports:
        - containerPort: 8080 
        resources: {}
          
status: {}
