apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"apache-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"apache"}},"template":{"metadata":{"labels":{"app":"apache"}},"spec":{"containers":[{"image":"httpd:latest","name":"apache","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2025-10-31T11:02:23Z"
  generation: 2
  name: apache-deployment
  namespace: default
  resourceVersion: "59746"
  uid: e700199a-d83d-4ba9-b68c-b09e817ceee5
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: httpd:latest
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
