apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"demo"},"name":"demo","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"demo"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"demo"}},"spec":{"containers":[{"image":"adikarthik/demo","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/demo1/api/v1/projects","port":9090},"initialDelaySeconds":30,"periodSeconds":30,"timeoutSeconds":1},"name":"demo","readinessProbe":{"failureThreshold":3,"initialDelaySeconds":30,"periodSeconds":30,"tcpSocket":{"port":9090},"timeoutSeconds":1},"resources":{}}]}}},"status":{}}
  creationTimestamp: "2025-11-01T09:17:03Z"
  generation: 17
  labels:
    app: demo
    name: demo
  name: demo
  namespace: default
  resourceVersion: "59817"
  uid: 89a04c7f-841e-47bc-961c-b78e180a4327
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
    spec:
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc1
      containers:
      - env:
        - name: dbstring
          valueFrom:
            configMapKeyRef:
              key: db
              name: demo
        image: adikarthik/demo
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /demo1/api/v1/projects
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: demo
        ports:
        - containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /demo1/api/v1/projects
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
          failureThreshold: 3
        volumeMounts:
        - name: vol1
          mountPath: /opt/vol1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-11-01T09:17:03Z"
    lastUpdateTime: "2025-11-06T06:45:03Z"
    message: ReplicaSet "demo-695d48488" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-09T09:36:17Z"
    lastUpdateTime: "2025-11-09T09:36:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 17
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
