apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: test
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        command:
        - sh
        - -c
        - echo $db 
        - env:
          - name: db
            valueFrom:
              configMapKeyRef:
                key: db
                name: demo
        resources: {}
      restartPolicy: Never
status: {}

