apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      initContainers:
      - image: busybox
        command:
        - sh
        - -c
        - sleep 5
        name: test1
      - image: busybox
        command:
        - sh
        - -c
        - echo "adi"
        name: test2
      - image: busybox
        command:
        - sh
        - -c
        - wget "google.com"
        name: test3
      - image: busybox
        command:
        - sh
        - -c
        - ls -lrt
        name: test4

      containers:
      - image: adikarthik/demo
        name: demo
        ports:
        - containerPort: 9090
        resources: 
          requests:
            cpu: "100m"
            memory: "1000Mi"
          limits:
            cpu: "500m"
            memory: "2000Mi"

status: {}
